restconf.host=localhost
restconf.port=8080
restconf.username=admin
restconf.password=admin
restconf.use-https=false
restconf.skip-ssl-verification=true
restconf.reboot-wait-seconds=5

spring.main.web-application-type=none